# Generated by Django 3.2.9 on 2022-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
