# Generated by Django 3.2.9 on 2021-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
